import { arrayTablePropField, defineMaterialPropForms, jsonPropField, option, propField, switchPropField, } from '../helpers';
const formComponentOptions = [
    option('输入框', 'vxe-input'),
    option('多行文本', 'vxe-textarea'),
    option('下拉选择', 'vxe-select'),
    option('开关', 'vxe-switch'),
    option('单选组', 'vxe-radio-group'),
    option('复选组', 'vxe-checkbox-group'),
    option('树选择', 'vxe-tree-select'),
    option('密码框', 'vxe-password-input'),
    option('数字输入', 'lc-number-input'),
    option('JSON 编辑器', 'lc-json-editor'),
    option('表格输入', 'lc-array-table'),
    option('子表单', 'lc-sub-form'),
];
const gridOverflowOptions = [
    option('默认', ''),
    option('省略', 'ellipsis'),
    option('标题提示', 'title'),
    option('气泡提示', 'tooltip'),
];
const alignOptions = [
    option('默认', ''),
    option('左对齐', 'left'),
    option('居中', 'center'),
    option('右对齐', 'right'),
];
const gridRendererPropFields = [
    { field: 'placeholder', label: 'placeholder', component: 'vxe-input' },
    { field: 'clearable', label: 'clearable', component: 'vxe-switch' },
    { field: 'disabled', label: 'disabled', component: 'vxe-switch' },
    { field: 'readonly', label: 'readonly', component: 'vxe-switch' },
];
const gridRendererObjectFields = [
    { field: 'name', label: 'name', component: 'vxe-input', props: { placeholder: 'VxeInput' } },
    {
        field: 'props',
        label: 'props',
        component: 'lc-sub-form',
        props: { fields: gridRendererPropFields },
    },
    {
        field: 'attrs',
        label: 'attrs',
        component: 'lc-sub-form',
        props: { fields: gridRendererPropFields },
    },
];
const gridColumnParamsFields = [
    { field: 'type', label: 'type', component: 'vxe-input' },
    { field: 'emptyText', label: 'emptyText', component: 'vxe-input' },
    { field: 'locale', label: 'locale', component: 'vxe-input' },
    {
        field: 'options',
        label: 'options',
        component: 'lc-sub-form',
        props: {
            fields: [
                { field: 'dateStyle', label: 'dateStyle', component: 'vxe-input' },
                { field: 'timeStyle', label: 'timeStyle', component: 'vxe-input' },
                { field: 'minimumFractionDigits', label: 'minimumFractionDigits', component: 'lc-number-input' },
                { field: 'maximumFractionDigits', label: 'maximumFractionDigits', component: 'lc-number-input' },
            ],
        },
    },
];
const buttonStatusOptions = [
    option('默认', ''),
    option('主要', 'primary'),
    option('成功', 'success'),
    option('警告', 'warning'),
    option('危险', 'danger'),
    option('信息', 'info'),
];
const buttonTypeOptions = [
    option('普通按钮', 'button'),
    option('提交', 'submit'),
    option('重置', 'reset'),
];
const runtimeContainerOptions = [
    option('容器', 'container'),
    option('分区', 'section'),
    option('弹框', 'modal'),
    option('抽屉', 'drawer'),
];
const placementOptions = [
    option('右侧', 'right'),
    option('左侧', 'left'),
];
const fieldColumns = [
    { field: 'field', title: '字段', minWidth: 110, placeholder: 'email' },
    { field: 'label', title: '标签', minWidth: 110, placeholder: '邮箱' },
    {
        field: 'component',
        title: '组件',
        component: 'vxe-select',
        minWidth: 132,
        options: formComponentOptions,
    },
    { field: 'placeholder', title: '占位提示', minWidth: 150 },
    { field: 'required', title: '必填', component: 'vxe-switch', width: 72 },
    { field: 'span', title: '跨列', width: 76, placeholder: '1' },
    { field: 'help', title: '帮助文本', minWidth: 140 },
    { field: 'optionsSourceKey', title: '选项数据源', minWidth: 130 },
    { field: 'optionLabel', title: '选项标签字段', minWidth: 120, placeholder: 'title' },
    { field: 'optionValue', title: '选项值字段', minWidth: 120, placeholder: 'id' },
    { field: 'optionChildren', title: '子节点字段', minWidth: 110, placeholder: 'children' },
    {
        field: 'optionsJson',
        title: '选项 JSON',
        component: 'lc-json-editor',
        minWidth: 220,
        placeholder: '[{"label":"A","value":"a"}]',
    },
    {
        field: 'propsJson',
        title: '属性 JSON',
        component: 'lc-json-editor',
        minWidth: 240,
        placeholder: '{"columns":[]}',
    },
];
const fieldDefaultRow = {
    field: 'field{{index}}',
    label: '字段 {{index}}',
    component: 'vxe-input',
    placeholder: '',
    required: false,
    span: '',
    help: '',
    optionsSourceKey: '',
    optionLabel: '',
    optionValue: '',
    optionChildren: '',
    optionsJson: '',
    propsJson: '',
};
const gridColumnRows = [
    { field: 'email', title: '邮箱', minWidth: '220' },
    { field: 'full_name', title: '姓名', minWidth: '160' },
    { field: 'role', title: '角色', minWidth: '120' },
];
const buttonRows = [
    {
        code: 'create',
        label: '新增',
        status: 'primary',
        type: 'button',
        eventName: 'buttonGroup.create',
        directivesJson: [],
        children: [],
    },
    {
        code: 'more',
        label: '更多',
        type: 'button',
        eventName: 'buttonGroup.more',
        directivesJson: [],
        children: [
            { code: 'import', label: '导入', type: 'button', eventName: 'buttonGroup.import' },
            { code: 'export', label: '导出', type: 'button', eventName: 'buttonGroup.export' },
        ],
    },
];
const formActionRows = [
    {
        code: 'submit',
        label: '保存',
        status: 'primary',
        type: 'submit',
        eventName: 'form.submit',
        directivesJson: [],
    },
    {
        code: 'reset',
        label: '重置',
        type: 'reset',
        eventName: 'form.reset',
        directivesJson: [],
    },
];
const buttonColumns = [
    { field: 'code', title: '编码', minWidth: 110, placeholder: 'create' },
    { field: 'label', title: '名称', minWidth: 110, placeholder: '新增' },
    {
        field: 'status',
        title: '状态',
        component: 'vxe-select',
        width: 96,
        options: buttonStatusOptions,
    },
    {
        field: 'type',
        title: '类型',
        component: 'vxe-select',
        width: 96,
        options: buttonTypeOptions,
    },
    { field: 'route', title: '路由', minWidth: 140, placeholder: '/dashboard/users' },
    { field: 'eventName', title: '事件名', minWidth: 160, placeholder: 'buttonGroup.click' },
    { field: 'icon', title: '图标', minWidth: 110, placeholder: 'ri-add-line' },
    { field: 'disabled', title: '禁用', component: 'vxe-switch', width: 72 },
    { field: 'plain', title: '朴素', component: 'vxe-switch', width: 72 },
    { field: 'text', title: '文本', component: 'vxe-switch', width: 72 },
    {
        field: 'directivesJson',
        title: '指令 JSON',
        component: 'lc-json-editor',
        minWidth: 220,
        placeholder: '[]',
    },
    {
        field: 'children',
        title: '子按钮 JSON',
        component: 'lc-json-editor',
        minWidth: 240,
        placeholder: '[{"code":"export","label":"导出"}]',
    },
];
const tabPaneRows = [
    { title: '基础信息', name: 'basic' },
    { title: '详细信息', name: 'detail' },
    { title: '操作记录', name: 'logs' },
];
export default defineMaterialPropForms([
    {
        componentKey: 'lowcode-grid',
        title: '表格属性',
        extendsVisualProps: true,
        fields: [
            arrayTablePropField({
                field: 'columns',
                path: 'columns',
                label: '表格列',
                defaultValue: gridColumnRows,
                addText: '新增列',
                rowKey: 'field',
                defaultRow: {
                    field: 'field{{index}}',
                    title: '列 {{index}}',
                    width: '',
                    minWidth: '120',
                    fixed: '',
                    align: '',
                    sortable: false,
                    visible: true,
                    formatter: '',
                },
                columns: [
                    { field: 'field', title: '字段', minWidth: 110, placeholder: 'email' },
                    { field: 'title', title: '标题', minWidth: 110, placeholder: '邮箱' },
                    { field: 'width', title: '宽度', width: 76, placeholder: '160' },
                    { field: 'minWidth', title: '最小宽度', width: 96, placeholder: '120' },
                    {
                        field: 'fixed',
                        title: '固定',
                        component: 'vxe-select',
                        width: 86,
                        options: [option('不固定', ''), option('左侧', 'left'), option('右侧', 'right')],
                    },
                    {
                        field: 'align',
                        title: '对齐',
                        component: 'vxe-select',
                        width: 90,
                        options: alignOptions,
                    },
                    { field: 'sortable', title: '排序', component: 'vxe-switch', width: 72 },
                    { field: 'treeNode', title: '树节点', component: 'vxe-switch', width: 72 },
                    { field: 'visible', title: '显示', component: 'vxe-switch', width: 72 },
                    { field: 'formatter', title: '格式化', minWidth: 150 },
                    {
                        field: 'showOverflow',
                        title: '溢出',
                        component: 'vxe-select',
                        minWidth: 110,
                        options: gridOverflowOptions,
                    },
                    {
                        field: 'filters',
                        title: '筛选 JSON',
                        component: 'lc-json-editor',
                        minWidth: 220,
                        placeholder: '[]',
                    },
                    {
                        field: 'cellRender',
                        title: '渲染对象',
                        component: 'lc-sub-form',
                        minWidth: 220,
                        defaultValue: {},
                        props: { fields: gridRendererObjectFields },
                    },
                    {
                        field: 'editRender',
                        title: '编辑对象',
                        component: 'lc-sub-form',
                        minWidth: 220,
                        defaultValue: {},
                        props: { fields: gridRendererObjectFields },
                    },
                    {
                        field: 'params',
                        title: '参数对象',
                        component: 'lc-sub-form',
                        minWidth: 220,
                        defaultValue: {},
                        props: { fields: gridColumnParamsFields },
                    },
                ],
                help: '维护表格列配置。复杂 formatter 仍可填 JSON 字符串。',
            }),
            propField({
                field: 'rowConfig.keyField',
                path: 'rowConfig.keyField',
                label: 'rowConfig.keyField',
                defaultValue: 'id',
            }),
            switchPropField({
                field: 'columnConfig.resizable',
                path: 'columnConfig.resizable',
                label: 'columnConfig.resizable',
                defaultValue: true,
            }),
            arrayTablePropField({
                field: 'gridEvents',
                path: 'gridEvents',
                label: 'VxeGrid 事件',
                defaultValue: [],
                addText: '新增事件',
                rowKey: 'key',
                defaultRow: {
                    key: 'row-click',
                    enabled: true,
                    eventName: '',
                    directivesJson: '[]',
                },
                columns: [
                    { field: 'key', title: '事件 Key', minWidth: 120, placeholder: 'row-click' },
                    { field: 'enabled', title: '启用', component: 'vxe-switch', width: 72 },
                    { field: 'eventName', title: '事件名', minWidth: 140, placeholder: 'grid.rowClick' },
                    {
                        field: 'directivesJson',
                        title: '指令 JSON',
                        component: 'lc-json-editor',
                        minWidth: 220,
                        placeholder: '[]',
                    },
                ],
            }),
            arrayTablePropField({
                field: 'rowActions',
                path: 'rowActions',
                label: '行按钮',
                defaultValue: [],
                addText: '新增行按钮',
                rowKey: 'code',
                defaultRow: {
                    code: 'rowAction{{index}}',
                    label: '操作 {{index}}',
                    status: '',
                    eventName: '',
                    icon: '',
                    disabled: false,
                    plain: false,
                    text: false,
                    directivesJson: [],
                },
                columns: buttonColumns,
            }),
        ],
    },
    {
        componentKey: 'lowcode-button-group',
        title: '按钮组属性',
        extendsVisualProps: true,
        fields: [
            arrayTablePropField({
                field: 'buttons',
                path: 'buttons',
                label: '按钮配置',
                defaultValue: buttonRows,
                addText: '新增按钮',
                rowKey: 'code',
                defaultRow: {
                    code: 'button{{index}}',
                    label: '按钮 {{index}}',
                    status: '',
                    type: 'button',
                    route: '',
                    eventName: '',
                    icon: '',
                    disabled: false,
                    plain: false,
                    text: false,
                    directivesJson: [],
                    children: [],
                },
                columns: buttonColumns,
                help: '维护按钮组及下拉子按钮。复杂事件指令和子按钮可用 JSON 编辑。',
            }),
        ],
    },
    {
        componentKey: 'lowcode-search-form',
        title: '查询表单属性',
        extendsVisualProps: true,
        fields: [
            arrayTablePropField({
                field: 'fields',
                path: 'fields',
                label: '查询字段',
                defaultValue: [],
                addText: '新增字段',
                rowKey: 'field',
                defaultRow: fieldDefaultRow,
                columns: fieldColumns,
            }),
        ],
    },
    {
        componentKey: 'lowcode-edit-form',
        title: '编辑表单属性',
        extendsVisualProps: true,
        fields: [
            propField({ field: 'blockId', path: 'blockId', label: '区块 ID', defaultValue: 'edit-form' }),
            propField({ field: 'title', path: 'title', label: '标题', defaultValue: '编辑信息' }),
            propField({ field: 'sourceKey', path: 'sourceKey', label: '读取数据源', defaultValue: '' }),
            propField({ field: 'submitSourceKey', path: 'submitSourceKey', label: '提交数据源', defaultValue: '' }),
            propField({ field: 'serviceName', path: 'serviceName', label: '服务名', defaultValue: 'admin' }),
            propField({ field: 'serviceMethod', path: 'serviceMethod', label: '读取方法', defaultValue: '' }),
            propField({ field: 'saveMethod', path: 'saveMethod', label: '保存方法', defaultValue: '' }),
            jsonPropField({ field: 'postDataJson', path: 'postDataJson', label: '请求参数', defaultValue: {} }),
            jsonPropField({ field: 'initialValuesJson', path: 'initialValuesJson', label: '初始值', defaultValue: {} }),
            arrayTablePropField({
                field: 'fields',
                path: 'fields',
                label: '表单字段',
                defaultValue: [],
                addText: '新增字段',
                rowKey: 'field',
                defaultRow: fieldDefaultRow,
                columns: fieldColumns,
            }),
            arrayTablePropField({
                field: 'formActions',
                path: 'formActions',
                label: '表单按钮',
                defaultValue: formActionRows,
                addText: '新增按钮',
                rowKey: 'code',
                defaultRow: {
                    code: 'action{{index}}',
                    label: '按钮 {{index}}',
                    status: '',
                    type: 'button',
                    route: '',
                    eventName: '',
                    disabled: false,
                    directivesJson: [],
                },
                columns: buttonColumns,
            }),
        ],
    },
    {
        componentKey: 'form',
        title: '普通表单属性',
        extendsVisualProps: true,
        fields: [
            propField({ field: 'blockId', path: 'blockId', label: '区块 ID', defaultValue: 'edit-form' }),
            propField({ field: 'title', path: 'title', label: '标题', defaultValue: '编辑信息' }),
            propField({ field: 'sourceKey', path: 'sourceKey', label: '读取数据源', defaultValue: '' }),
            propField({ field: 'submitSourceKey', path: 'submitSourceKey', label: '提交数据源', defaultValue: '' }),
            propField({ field: 'serviceName', path: 'serviceName', label: '服务名', defaultValue: 'admin' }),
            propField({ field: 'serviceMethod', path: 'serviceMethod', label: '读取方法', defaultValue: '' }),
            propField({ field: 'saveMethod', path: 'saveMethod', label: '保存方法', defaultValue: '' }),
            jsonPropField({ field: 'postDataJson', path: 'postDataJson', label: '请求参数', defaultValue: {} }),
            jsonPropField({ field: 'initialValuesJson', path: 'initialValuesJson', label: '初始值', defaultValue: {} }),
            arrayTablePropField({
                field: 'fields',
                path: 'fields',
                label: '表单字段',
                defaultValue: [],
                addText: '新增字段',
                rowKey: 'field',
                defaultRow: fieldDefaultRow,
                columns: fieldColumns,
            }),
            arrayTablePropField({
                field: 'formActions',
                path: 'formActions',
                label: '表单按钮',
                defaultValue: formActionRows,
                addText: '新增按钮',
                rowKey: 'code',
                defaultRow: {
                    code: 'action{{index}}',
                    label: '按钮 {{index}}',
                    status: '',
                    type: 'button',
                    route: '',
                    eventName: '',
                    disabled: false,
                    directivesJson: [],
                },
                columns: buttonColumns,
            }),
            arrayTablePropField({
                field: 'slots.default.children',
                path: 'slots.default.children',
                label: '默认插槽节点',
                defaultValue: [],
                addText: '新增节点',
                rowKey: 'value',
                defaultRow: {
                    label: '节点 {{index}}',
                    value: 'node{{index}}',
                    comments: '',
                },
                columns: [
                    { field: 'label', title: '显示值', minWidth: 110 },
                    { field: 'value', title: '绑定值', minWidth: 110 },
                    { field: 'comments', title: '备注', minWidth: 140 },
                ],
            }),
        ],
    },
    {
        componentKey: 'vxe-tabs',
        title: '页签属性',
        extendsVisualProps: true,
        fields: [
            arrayTablePropField({
                field: 'panes',
                path: 'panes',
                label: 'TabPane 操作表格',
                defaultValue: tabPaneRows,
                addText: '新增页签',
                rowKey: 'name',
                defaultRow: {
                    title: '页签 {{index}}',
                    name: 'tab{{index}}',
                    icon: '',
                    titleWidth: '',
                    preload: false,
                },
                columns: [
                    { field: 'title', title: '标题', minWidth: 110, placeholder: '基础信息' },
                    { field: 'name', title: '标识', minWidth: 96, placeholder: 'basic' },
                    { field: 'icon', title: '图标', minWidth: 96, placeholder: 'ri-user-line' },
                    { field: 'titleWidth', title: '标题宽度', width: 88, placeholder: '120' },
                    { field: 'preload', title: '预加载', component: 'vxe-switch', width: 72 },
                ],
                help: '维护页签 pane 列表，标识会用于页签 name 和内容插槽绑定。',
            }),
        ],
    },
    {
        componentKey: 'lowcode-modal',
        title: '弹框属性',
        extendsVisualProps: false,
        fields: [
            propField({
                field: 'blockId',
                path: 'blockId',
                label: '区块 ID',
                component: 'vxe-input',
                defaultValue: 'modal-block',
            }),
            propField({
                field: 'title',
                path: 'title',
                label: '标题',
                component: 'vxe-input',
                defaultValue: '弹框',
            }),
            propField({
                field: 'description',
                path: 'description',
                label: '描述',
                component: 'vxe-textarea',
                defaultValue: '',
            }),
            switchPropField({ field: 'open', path: 'open', label: '默认打开', defaultValue: false }),
            propField({
                field: 'width',
                path: 'width',
                label: '宽度',
                component: 'vxe-input',
                defaultValue: '640',
            }),
        ],
    },
    {
        componentKey: 'layout',
        title: '布局容器属性',
        extendsVisualProps: true,
        fields: [
            propField({
                field: 'blockId',
                path: 'blockId',
                label: '区块 ID',
                component: 'vxe-input',
                defaultValue: 'container-block',
            }),
            propField({
                field: 'runtimeKind',
                path: 'runtimeKind',
                label: '运行形态',
                component: 'vxe-select',
                defaultValue: 'container',
                options: runtimeContainerOptions,
            }),
            propField({
                field: 'title',
                path: 'title',
                label: '标题',
                component: 'vxe-input',
                defaultValue: '',
            }),
            propField({
                field: 'description',
                path: 'description',
                label: '描述',
                component: 'vxe-textarea',
                defaultValue: '',
            }),
            switchPropField({ field: 'open', path: 'open', label: '默认打开', defaultValue: false }),
            switchPropField({ field: 'panel', path: 'panel', label: '面板样式', defaultValue: false }),
            propField({
                field: 'width',
                path: 'width',
                label: '弹框/抽屉宽度',
                component: 'vxe-input',
                defaultValue: '',
            }),
            propField({
                field: 'placement',
                path: 'placement',
                label: '抽屉方向',
                component: 'vxe-select',
                defaultValue: 'right',
                options: placementOptions,
            }),
            propField({
                field: 'gutter',
                path: 'gutter',
                label: '列间隔',
                component: 'vxe-input',
                defaultValue: '',
            }),
            propField({
                field: 'slots',
                path: 'slots',
                label: '列比例',
                component: 'vxe-input',
                valueKind: 'layoutSlots',
                defaultValue: '12:12',
                help: '输入任意 span 比例，例如 5:7:12；也可以在画布中拖动列间手柄调整，或添加/删除列。',
            }),
        ],
    },
]);
