/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatPopup: typeof import('./../components/ChatPopup.vue')['default']
    ContentRenderer: typeof import('./../components/ContentRenderer.vue')['default']
    DocsScreen: typeof import('./../components/DocsScreen.vue')['default']
    JsonDialogInput: typeof import('./../../packages/lowcode-framework/src/components/JsonDialogInput.vue')['default']
    LowCodeBlockChildren: typeof import('./../../packages/lowcode-framework/src/components/LowCodeBlockChildren.vue')['default']
    LowCodeBlockRenderer: typeof import('./../../packages/lowcode-framework/src/components/LowCodeBlockRenderer.vue')['default']
    LowCodeContextDrawerPanel: typeof import('./../../packages/lowcode-framework/src/components/LowCodeContextDrawerPanel.vue')['default']
    LowCodeForm: typeof import('./../../packages/lowcode-framework/src/components/LowCodeForm.vue')['default']
    LowCodeFormField: typeof import('./../../packages/lowcode-framework/src/components/LowCodeFormField.vue')['default']
    LowCodeFormLayout: typeof import('./../../packages/lowcode-framework/src/components/LowCodeFormLayout.vue')['default']
    LowCodeGrid: typeof import('./../../packages/lowcode-framework/src/components/LowCodeGrid.vue')['default']
    LowCodeOverlayHost: typeof import('./../../packages/lowcode-framework/src/components/LowCodeOverlayHost.vue')['default']
    LowCodePageRenderer: typeof import('./../../packages/lowcode-framework/src/components/LowCodePageRenderer.vue')['default']
    LowCodeTreeItem: typeof import('./../../packages/lowcode-framework/src/components/LowCodeTreeItem.vue')['default']
    LowCodeVisualDesigner: typeof import('./../../packages/lowcode-framework/src/components/LowCodeVisualDesigner.vue')['default']
    NotificationBell: typeof import('./../components/NotificationBell.vue')['default']
    RouteCacheOutlet: typeof import('./../components/RouteCacheOutlet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteFooter: typeof import('./../components/SiteFooter.vue')['default']
    SiteHeader: typeof import('./../components/SiteHeader.vue')['default']
    VisualEditorProvider: typeof import('./../../packages/lowcode-framework/src/components/VisualEditorProvider.vue')['default']
  }
}

// For TSX support
declare global {
  const ChatPopup: typeof import('./../components/ChatPopup.vue')['default']
  const ContentRenderer: typeof import('./../components/ContentRenderer.vue')['default']
  const DocsScreen: typeof import('./../components/DocsScreen.vue')['default']
  const JsonDialogInput: typeof import('./../../packages/lowcode-framework/src/components/JsonDialogInput.vue')['default']
  const LowCodeBlockChildren: typeof import('./../../packages/lowcode-framework/src/components/LowCodeBlockChildren.vue')['default']
  const LowCodeBlockRenderer: typeof import('./../../packages/lowcode-framework/src/components/LowCodeBlockRenderer.vue')['default']
  const LowCodeContextDrawerPanel: typeof import('./../../packages/lowcode-framework/src/components/LowCodeContextDrawerPanel.vue')['default']
  const LowCodeForm: typeof import('./../../packages/lowcode-framework/src/components/LowCodeForm.vue')['default']
  const LowCodeFormField: typeof import('./../../packages/lowcode-framework/src/components/LowCodeFormField.vue')['default']
  const LowCodeFormLayout: typeof import('./../../packages/lowcode-framework/src/components/LowCodeFormLayout.vue')['default']
  const LowCodeGrid: typeof import('./../../packages/lowcode-framework/src/components/LowCodeGrid.vue')['default']
  const LowCodeOverlayHost: typeof import('./../../packages/lowcode-framework/src/components/LowCodeOverlayHost.vue')['default']
  const LowCodePageRenderer: typeof import('./../../packages/lowcode-framework/src/components/LowCodePageRenderer.vue')['default']
  const LowCodeTreeItem: typeof import('./../../packages/lowcode-framework/src/components/LowCodeTreeItem.vue')['default']
  const LowCodeVisualDesigner: typeof import('./../../packages/lowcode-framework/src/components/LowCodeVisualDesigner.vue')['default']
  const NotificationBell: typeof import('./../components/NotificationBell.vue')['default']
  const RouteCacheOutlet: typeof import('./../components/RouteCacheOutlet.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SiteFooter: typeof import('./../components/SiteFooter.vue')['default']
  const SiteHeader: typeof import('./../components/SiteHeader.vue')['default']
  const VisualEditorProvider: typeof import('./../../packages/lowcode-framework/src/components/VisualEditorProvider.vue')['default']
}